services:
  ad-calendarMeeting:
    build:
      context: .
    container_name: ad-calendarMeeting
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ad-calendarmeeting-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: ad-calendarmeeting
    ports:
      - "27111:27017"
    volumes:
      - ad-calendarmeeting-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: ad-calendarmeeting-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ad-calendarmeeting
    ports:
      - "5112:5432"
    volumes:
      - ad-calendarmeeting-postgresql:/data/db/postgresql

volumes:
  ad-calendarmeeting-mongodb:
    driver: local
  ad-calendarmeeting-postgresql:
    driver: local
